"""import pipeline

Revision ID: 7683933547a6
Revises: 0002
Create Date: 2026-08-25 06:25:39.488397
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_import_batches_owner_created",
        "import_batches",
        ["owner_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("suspected_of_asset_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suspected_of_asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_duplicate_candidates_owner_status",
        "duplicate_candidates",
        ["owner_id", "status"],
        unique=False,
    )
    op.create_table(
        "import_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("detected_format", sa.String(length=8), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("work_id", sa.UUID(), nullable=True),
        sa.Column(
            "match_evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_import_items_batch", "import_items", ["batch_id"], unique=False)
    op.create_index(
        "ix_import_items_owner_status", "import_items", ["owner_id", "status"], unique=False
    )
    op.add_column("assets", sa.Column("work_id", sa.UUID(), nullable=True))
    op.create_index("ix_assets_work", "assets", ["work_id"], unique=False)
    op.create_foreign_key(
        "fk_assets_work", "assets", "works", ["work_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_assets_work", "assets", type_="foreignkey")
    op.drop_index("ix_assets_work", table_name="assets")
    op.drop_column("assets", "work_id")
    op.drop_index("ix_import_items_owner_status", table_name="import_items")
    op.drop_index("ix_import_items_batch", table_name="import_items")
    op.drop_table("import_items")
    op.drop_index("ix_duplicate_candidates_owner_status", table_name="duplicate_candidates")
    op.drop_table("duplicate_candidates")
    op.drop_index("ix_import_batches_owner_created", table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
