"""normalization runs

Revision ID: f5528852de90
Revises: 0003
Create Date: 2026-08-25 08:22:34.985032
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "normalization_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("input_asset_id", sa.UUID(), nullable=False),
        sa.Column("derivative_asset_id", sa.UUID(), nullable=True),
        sa.Column("input_sha256", sa.String(length=64), nullable=True),
        sa.Column("output_sha256", sa.String(length=64), nullable=True),
        sa.Column("profile", sa.String(length=32), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("normalizer_version", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column(
            "actions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["derivative_asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["input_asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_normalization_runs_input", "normalization_runs", ["input_asset_id"], unique=False
    )
    op.create_index(
        "ix_normalization_runs_owner_created",
        "normalization_runs",
        ["owner_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_normalization_runs_idempotent",
        "normalization_runs",
        ["input_asset_id", "profile", "profile_version", "normalizer_version"],
        unique=True,
        postgresql_where=sa.text("state NOT IN ('failed', 'needs_review')"),
    )
    op.add_column(
        "assets",
        sa.Column("is_preferred", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "is_preferred")
    op.drop_index(
        "uq_normalization_runs_idempotent",
        table_name="normalization_runs",
        postgresql_where=sa.text("state NOT IN ('failed', 'needs_review')"),
    )
    op.drop_index("ix_normalization_runs_owner_created", table_name="normalization_runs")
    op.drop_index("ix_normalization_runs_input", table_name="normalization_runs")
    op.drop_table("normalization_runs")
    # ### end Alembic commands ###
