"""ai proposals cache and corrections

Revision ID: 3f3d163a3090
Revises: 0004
Create Date: 2026-08-25 10:46:49.723151
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("digest_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_ai_proposals_cache",
        "ai_proposals",
        ["digest_hash", "model", "prompt_version", "schema_version"],
        unique=True,
    )
    op.create_table(
        "ai_corrections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("import_item_id", sa.UUID(), nullable=True),
        sa.Column("digest_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "proposal",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("applied", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["import_item_id"], ["import_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_corrections_owner_created",
        "ai_corrections",
        ["owner_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_corrections_owner_created", table_name="ai_corrections")
    op.drop_table("ai_corrections")
    op.drop_index("uq_ai_proposals_cache", table_name="ai_proposals")
    op.drop_table("ai_proposals")
    # ### end Alembic commands ###
